title: "아기 발음 기록장"
description: "우리 아기의 소중한 말하기 성장 기록"
baseurl: ""
url: ""
theme: null
plugins:
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
